export function downloadExcelReport(metrics) {
    const csvContent = "data:text/csv;charset=utf-8," 
        + "METRIC,VALUE\n"
        + `Total Time Windows Evaluated,${metrics.totalWindows}\n`
        + `Anomalous Windows Detected,${metrics.anomalousWindows}\n`
        + `Current Flow Throughput,${metrics.flowThroughput}\n`
        + `Latest Peak Risk Probability,${metrics.peakRisk}\n`
        + `Active Session ID,${metrics.sessionId}\n`;
        
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Sentinel_AI_Report_${new Date().getTime()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

export function downloadPDFReport(metrics) {
    const htmlContent = `
        <html>
            <head>
                <title>Sentinel AI - Live Session Report</title>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; }
                    h1 { color: #065f46; border-bottom: 2px solid #065f46; padding-bottom: 10px; font-size: 24px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 30px; }
                    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                    th { background-color: #f8f9fa; color: #555; }
                    .anomaly { color: #dc2626; font-weight: bold; }
                    .footer { margin-top: 50px; font-size: 12px; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }
                </style>
            </head>
            <body>
                <h1>Sentinel AI - Live Session Ingestion Report</h1>
                <p><strong>Generated on:</strong> ${new Date().toLocaleString()}</p>
                <p><strong>Session ID:</strong> ${metrics.sessionId}</p>
                
                <table>
                    <thead>
                        <tr>
                            <th>Metric</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Total Time Windows Evaluated</td>
                            <td>${metrics.totalWindows} windows</td>
                        </tr>
                        <tr>
                            <td>Anomalous Windows Detected</td>
                            <td class="${metrics.anomalousWindows > 0 ? 'anomaly' : ''}">${metrics.anomalousWindows}</td>
                        </tr>
                        <tr>
                            <td>Current Flow Throughput</td>
                            <td>${metrics.flowThroughput} flows/min</td>
                        </tr>
                        <tr>
                            <td>Latest Peak Risk Probability</td>
                            <td class="${parseFloat(metrics.peakRisk) > 50 ? 'anomaly' : ''}">${metrics.peakRisk}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="footer">
                    Automated report generated by Sentinel AI Cyber World Model.
                </div>
                <script>
                    window.onload = function() { 
                        setTimeout(function() { window.print(); window.close(); }, 250);
                    }
                </script>
            </body>
        </html>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.open();
        printWindow.document.write(htmlContent);
        printWindow.document.close();
    } else {
        alert("Please allow pop-ups to download the PDF report.");
    }
}